import 'package:home_rent/constants/app_images.dart';

import '../features/home/domain/models/house.dart';

List<House> housesNearby = [
  House(
    id: '1',
    name: 'Dreamsville House',
    image: AppImages.dreamsvilleHouse,
    gallery: [
      AppImages.galleryImage1,
      AppImages.galleryImage2,
      AppImages.galleryImage3,
      AppImages.galleryImage4
    ],
    distance: "18 km",
    address: 'Jl. Sultan Iskandar Muda, Jakarta selatan',
    price: 'Rp. 2.500.000.000 / Year',
    description: 'A cozy cottage with a beautiful garden.',
    bedrooms: 6,
    bathrooms: 4,
    latitude: -6.200000,
    longitude: 106.816666,
    ownerName: 'Garry Allen',
    ownerEmail: 'john@example.com',
    ownerPhone: '555-1234',
    ownerImage: AppImages.ownerImage,
  ),
  House(
    id: '2',
    name: 'Ascot House',
    image: AppImages.ascotsHouse,
    gallery: [
      AppImages.galleryImage1,
      AppImages.galleryImage2,
      AppImages.galleryImage3,
      AppImages.galleryImage4
    ],
    distance: "16 km",
    address: 'Jl. Cilandak Tengah',
    price: 'Rp. 2.500.000.000 / Year',
    description: 'A cozy cottage with a beautiful garden.',
    bedrooms: 6,
    bathrooms: 4,
    latitude: -6.200000,
    longitude: 106.816666,
    ownerName: 'Garry Allen',
    ownerEmail: 'john@example.com',
    ownerPhone: '555-1234',
    ownerImage: AppImages.ownerImage,
  ),
  House(
    id: '3',
    name: 'Dreamsville House',
    image: AppImages.seaBreezes,
    gallery: [
      AppImages.galleryImage1,
      AppImages.galleryImage2,
      AppImages.galleryImage3,
      AppImages.galleryImage4
    ],
    distance: "19 km",
    address: 'Jl. Sultan Iskandar Muda, Jakarta selatan',
    price: 'Rp. 2.500.000.000 / Year',
    description: 'A cozy cottage with a beautiful garden.',
    bedrooms: 6,
    bathrooms: 4,
    latitude: -6.200000,
    longitude: 106.816666,
    ownerName: 'Garry Allen',
    ownerEmail: 'john@example.com',
    ownerPhone: '555-1234',
    ownerImage: AppImages.ownerImage,
  ),
];
List<House> bestForYou = [
  House(
    id: '1',
    name: 'Dreamsville House',
    image: AppImages.orchadHouse,
    gallery: [
      AppImages.galleryImage1,
      AppImages.galleryImage2,
      AppImages.galleryImage3,
      AppImages.galleryImage4
    ],
    distance: "18 km",
    address: 'Jl. Sultan Iskandar Muda, Jakarta selatan',
    price: 'Rp. 2.500.000.000 / Year',
    description: 'A cozy cottage with a beautiful garden.',
    bedrooms: 6,
    bathrooms: 4,
    latitude: -6.200000,
    longitude: 106.816666,
    ownerName: 'Garry Allen',
    ownerEmail: 'john@example.com',
    ownerPhone: '555-1234',
    ownerImage: AppImages.ownerImage,
  ),
  House(
    id: '2',
    name: 'The Hollies House',
    image: AppImages.holliesHouse,
    gallery: [
      AppImages.galleryImage1,
      AppImages.galleryImage2,
      AppImages.galleryImage3,
      AppImages.galleryImage4
    ],
    distance: "18 km",
    address: 'Jl. Sultan Iskandar Muda, Jakarta selatan',
    price: 'Rp. 2.000.000.000 / Year',
    description: 'A cozy cottage with a beautiful garden.',
    bedrooms: 5,
    bathrooms: 2,
    latitude: -6.200000,
    longitude: 106.816666,
    ownerName: 'Garry Allen',
    ownerEmail: 'john@example.com',
    ownerPhone: '555-1234',
    ownerImage: AppImages.ownerImage,
  ),
  House(
    id: '2',
    name: 'Sea Breezes House',
    image: AppImages.seaBreezes,
    gallery: [
      AppImages.galleryImage1,
      AppImages.galleryImage2,
      AppImages.galleryImage3,
      AppImages.galleryImage4
    ],
    distance: "18 km",
    address: 'Jl. Sultan Iskandar Muda, Jakarta selatan',
    price: 'Rp. 900.000.000 / Year',
    description: 'A cozy cottage with a beautiful garden.',
    bedrooms: 2,
    bathrooms: 2,
    latitude: -6.200000,
    longitude: 106.816666,
    ownerName: 'Garry Allen',
    ownerEmail: 'john@example.com',
    ownerPhone: '555-1234',
    ownerImage: AppImages.ownerImage,
  ),
];
